### PR TITLE
fix: No matching function for call to 'transformImage' (#342)

### PR DESCRIPTION
**Pull request by chj-damon**
fix error when archive app in xcode

### CODE REVIEW

**Comment by robingullo** [comment]
Thank you for your contribution. We don't want to modify the signature of the methods, since they need to be compatible with the architecture's codegen. Could you try instead in line 53 of `ImageResizer.mm`:
```diff
-            NSDictionary * response =  transformImage(image, uri, [rotation integerValue], newSize, fullPath, format, (int)quality, keepMeta, @{@"mode": mode, @"onlyScaleDown": [NSNumber numberWithBool:onlyScaleDown]});
+            NSDictionary * response =  transformImage(image, uri, [rotation integerValue], newSize, fullPath, format, (int)quality, [keepMeta boolValue], @{@"mode": mode, @"onlyScaleDown": [NSNumber numberWithBool:onlyScaleDown]});
```

**Comment by chj-damon** [comment]
@robingullo I tried this solution in xcode 13.4.1 and it works.

also, I tried not change any code and it also works in xcode 14.2/m2 chip. I don't why

**Comment by chj-damon** [comment]
updated.

**Comment by taboulot** [comment]
I have Xcode 14.0.1 and no error occurred without the fix but I have a warning.

I think some configurations changed in the Xcode compiler during migration from 13.x -> 14.x with the consequence that this error in version 13 was only a warning in version 14.

Anyway, this PR fix a syntax error, improve the code & fix #342.
