### ISSUE TITLE
Undefined symbols for architecture x86_64:

### ISSUE THREAD

**Issue by fega** [bamlab/react-native-image-resizer#204]
Hello, recently I tried to reinstall cocoapods but for some reason it obliges me to update the dependencies or otherwise installation fails.

so using react-native-image-resizer 1.10 compilation fails with the following error:

```
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_RCTImageLoader", referenced from:
      objc-class-ref in RCTImageResizer.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by PierreCapo** [comment]
Hello @fega , I will investigate it. What is your version of react-native ?

**Comment by fega** [comment]
0.61.2

**Comment by fega** [comment]
thanks so much for the quick response :)

**Comment by PierreCapo** [comment]
So, after investigation:
- In the last release `1.1.0` was merged this pr: https://github.com/bamlab/react-native-image-resizer/pull/198 that introduces RCTImageLoader in `react-native-image-resizer` because we were using an API that get deprecated.
- I tried with the [example](https://github.com/bamlab/react-native-image-resizer/tree/master/example) app (which is 0.61.1) and it's working well, I don't have errors.
- Check with XCode your pod folder, but you should have somewhere there a RCTImageLoader file there that would expose this module. I suspect for whatever reason you don't have it, and this is why this is crashing. See image attached:
![image](https://user-images.githubusercontent.com/26744253/67718508-34735c00-f9d0-11e9-96e6-9fbdba9f051d.png)

**Comment by fega** [comment]
@PierreCapo Amazing thank so much for taking the time...

after research i found that the file is there.. but for unknown reasons xcode wasn't able to build the app...

what I did is just uninstall and reinstall a couple of times and at the end it worked 😅 ,

**Comment by stu-dev** [comment]
I had this exact same issue when upgrading to 1.1.0 and trying to build with react-native 0.61.2/0.61.3/0.61.4

Tried various combinations of re-installing/linking etc but gave up and just downgraded to 1.0.1

@fega was there something else specific that you did?
